CREATE TABLE PARTIDA IF NOT EXISTS(
ID integer primary key ,
TIME_M varchar(50) not null,
TIME_V varchar(50) not null,
DATA_PARTIDA timestamp not null,
PLACAR_MANDANTE integer not null,
PLACAR_VISITANTE integer not null);

INSERT INTO PARTIDA (ID, TIME_M, TIME_V, DATA_PARTIDA, PLACAR_MANDANTE, PLACAR_VISITANTE) VALUES (1, 'Brasil', 'Argentina', '2022-11-24', 1, 0);
INSERT INTO PARTIDA (ID, TIME_M, TIME_V, DATA_PARTIDA, PLACAR_MANDANTE, PLACAR_VISITANTE) VALUES (2, 'França', 'Inglaterra', '2022-11-26', 4, 2);
INSERT INTO PARTIDA (ID, TIME_M, TIME_V, DATA_PARTIDA, PLACAR_MANDANTE, PLACAR_VISITANTE) VALUES (3, 'Alemanha', 'Catar', '2022-11-29', 7, 0);
INSERT INTO PARTIDA (ID, TIME_M, TIME_V, DATA_PARTIDA, PLACAR_MANDANTE, PLACAR_VISITANTE) VALUES (4, 'Suíça', 'Sérvia', '2022-12-01', 1, 2);
INSERT INTO PARTIDA (ID, TIME_M, TIME_V, DATA_PARTIDA, PLACAR_MANDANTE, PLACAR_VISITANTE) VALUES (5, 'Senegal', 'Dinamarca', '2022-12-04', 1, 1);